### ISSUE TITLE
Wrong transformation or rotation

### ISSUE THREAD

**Issue by campione23** [VCityTeam/py3dtilers#105]
In the geojson-tiler functionality there is an error in the positioning of the 3D tilers within Cesium (EPSG: 4978), as shown in the below image.

I followed the tutorial 'Create 3DTiles from OpenStreetMap data' but the result is not correct ( crs_in = EPSG:2154 crs_out = EPSG:4978).

What could be the problem?

Thanks in advance.

![image](https://user-images.githubusercontent.com/44543066/181259755-512d3a4e-b7e9-4ff2-98c0-2f215f90e85e.png)

**Comment by utraum** [comment]
I have the same problem   crs_in = EPSG:28532, crs_out = EPSG:4978

![Bildschirmfoto_2022-07-28_13-04-26](https://user-images.githubusercontent.com/22564696/181490764-ab4230aa-d72c-4fae-a72c-933ec4377126.png)

**Comment by LorenzoMarnat** [comment]
It seems that reprojection was broken with the [PR 99](https://github.com/VCityTeam/py3dtilers/pull/99).

I'll try to find a fix.

For now, you can use d2b560e9853fdd5e45934cf5d364b6aa01d13761 (the commit before the PR) where reprojection works well:

```bash
git checkout d2b560e9853fdd5e45934cf5d364b6aa01d13761
```

**Comment by LorenzoMarnat** [comment]
Since I can't find a fast fix, I've reverted PR #99 on master. I'll rework this PR later.

For now, the problem should be fixed on master.
