### ISSUE TITLE
Create texture LODs

### ISSUE THREAD

**Issue by LorenzoMarnat** [VCityTeam/py3dtilers#109]
An efficient way to be able to visualize large textured tilesets would be to create texture LODs.

## Downsize images

A first step would be to give the possibility to [downsize](https://clouard.users.greyc.fr/Pantheon/experiments/rescaling/index-en.html) images

```python
image = image.resize((int(image.width/10), int(image.height/10)))
```

I tried to downsample Lyon 1er textures, and it seems to reduce the size on disk of the tileset and RAM usage by 20.

Those tests were made on the branch [texture_lods](https://github.com/VCityTeam/py3dtilers/tree/texture_lods).

**Comment by LorenzoMarnat** [comment]
A demo of texture LODs is available [here](https://py3dtilers-demo.vcityliris.data.alpha.grandlyon.com/html/textured.html)

**Comment by jailln** [comment]
Nice! :+1:  How have you implemented it in the end ? (I remember several methods were considered)

**Comment by LorenzoMarnat** [comment]
For now, I'm using Pillow's [Nearest Neighbor Resampling](https://clouard.users.greyc.fr/Pantheon/experiments/rescaling/index-en.html#nearest) to downsize the texture images:

```py
atlasImg = atlasImg.resize((int(atlasImg.width/downsample_factor), int(atlasImg.height/downsample_factor)))
```

For each textured tile, I create 4 parent tiles with the same geometry but a smaller texture image. The root tile has the smallest image (and the hightest downsample_factor), the leaf tile has the biggest image (and the smallest downsample_factor):

```py
            node = GeometryNode(group.feature_list, geometric_error=1, with_texture=True)
            root_node = node
            factor = 3
            for _ in range(0,4):
                textured_node = GeometryNode(copy.deepcopy(group.feature_list), geometric_error=int(factor/3), with_texture=True, downsample_factor=factor)
                textured_node.add_child_node(root_node)
                root_node = textured_node
                factor += 10
```

```mermaid
graph TD;
   Tileset-->Tile1_LOD1-->Tile1_LOD2-->Tile1_LOD3-->Tile1_LOD4-->Tile1;
   Tileset-->Tile2_LOD1-->Tile2_LOD2-->Tile2_LOD3-->Tile2_LOD4-->Tile2;
```

Everything is hardcoded for now though (the geometric errors, the downsample factors, the number of LODs)

**Comment by jailln** [comment]
Ok, thanks for the detailed explaination!

> Everything is hardcoded for now though (the geometric errors, the downsample factors, the number of LODs)

Still, it's nice to see texture LODs starting to being implemented in py3dtilers :)

**Comment by LorenzoMarnat** [comment]
You welcome!

I'll try to work on this feature in the next few months, the results are really promising
