### ISSUE TITLE
Invalid tiles when using Batch Table Hierarchy in CityTiler

### ISSUE THREAD

**Issue by LorenzoMarnat** [VCityTeam/py3dtilers#11]
When creating tiles with [batch table hierarchy](https://github.com/VCityTeam/py3dtilers/blob/master/py3dtilers/CityTiler/database_accesses_batch_table_hierarchy.py#L86) with the CityTiler (in its current state on Master), the resulting tileset can't be loaded in UD-Viz due to this error:
![image](https://user-images.githubusercontent.com/32875283/124286779-93975580-db4f-11eb-9693-31bc52321b85.png)

I can't tell if the Batch Table Hierarchy is broken on the creation side (CityTiler) or on the loading side (UD-Viz). Did this feature even work one day ? or is it unfinished job ?

To create a tileset with BTH:
```
citygml-tiler --with_BTH
```

**Comment by jailln** [comment]
You need to register the extension parser in iTowns and add it to the tileset using the extension; try something similar to the syntax used here: https://github.com/iTowns/itowns/blob/master/examples/3dtiles_batch_table.html#L52

**Comment by LorenzoMarnat** [comment]
Thanks, it works perfectly !

The extension was actually registered in [DemoFull](https://github.com/VCityTeam/UD-Viz-demo/blob/master/DemoFull/src/Helpers/BaseDemo.js#L624), I only had to add the extension in the [config.json](https://github.com/VCityTeam/UD-Viz-demo/blob/master/DemoFull/assets/config/config.json#L65):  
![image](https://user-images.githubusercontent.com/32875283/124435480-53b1b780-dd75-11eb-87d7-56e3989619db.png)
