### ISSUE TITLE
[ObjTiler] Unsupported format T2F_C3F_V3F

### ISSUE THREAD

**Issue by JCAELA** [VCityTeam/py3dtilers#115]
Hi

I am new with py3dtilers. I am trying to convert 3d models in obj format into tiles using the obj-tiler.
I followed the instructions in the readmes but I get the:
 "Unsupported format T2F_C3F_V3F" or "Unsupported format T2F_N3F_V3F" followed by "No .obj found in <path>". 

![py3dtiler](https://user-images.githubusercontent.com/100201026/203937787-204b76ff-a026-476f-a531-6a3ea85e8ecb.PNG)

I tried with several models and the result is the same. I am quite sure the models are in .obj format.

I would like to understand what is going on and how I can overcome this issue.

Thanks

**Comment by LorenzoMarnat** [comment]
Hello

'T2F_C3F_V3F' corresponds to the format of each vertex (in this case, a vertex has: 2 texture coords, 3 color coords and 3 position coords). In [this commit](https://github.com/VCityTeam/py3dtilers/commit/aa5c85521d1282148704598f4985c728c791d23a), I added support for 'T2F_C3F_V3F'.

'T2F_N3F_V3F' should already be supported. py3dtilers uses [PyWavefront](https://github.com/pywavefront/PyWavefront) to read and parse the OBJ models. Sometimes, this library isn't able to parse the model, but I can't say why and how to fix it.

Hope it helps
