### ISSUE TITLE
Unsupported format T2F_C3F_V3F

### ISSUE THREAD

**Issue by JCAELA** [VCityTeam/py3dtilers#116]
Hi

I am new with py3dtilers. I am trying to convert 3d models in obj format into tiles using the obj-tiler.
I followed the instructions in the readmes but I get the:
 "Unsupported format T2F_C3F_V3F" or "Unsupported format T2F_N3F_V3F" followed by "No .obj found in <path>". 

![py3dtiler](https://user-images.githubusercontent.com/100201026/203937787-204b76ff-a026-476f-a531-6a3ea85e8ecb.PNG)

I tried with several models and the result is the same. I am quite sure the models are in .obj format.

I would like to understand what is going on and how I can overcome this issue.

Thanks

**Comment by LorenzoMarnat** [comment]
Duplicate of #115
