### ISSUE TITLE
[Feature Request] IDs filter

### ISSUE THREAD

**Issue by jlai2021** [VCityTeam/py3dtilers#123]
Hi developers, would it be possible to provide an ID filter function that only filter out a specified or many specified CityGML IDs and keep the rest IDs in tiling?

In the current design, it keeps those IDs. 
``ID filter
The flag --ids allows to keep only the selected CityObject(s). The flag must be followed by a list of CityGML IDs.``

Many thanks!

**Comment by LorenzoMarnat** [comment]
Hello, indeed it would be useful to have 2 filter functions, one to keep IDs and one to exclude IDs. I think it shouldn't be too difficult to implement for the CityGML tiler

**Comment by LorenzoMarnat** [comment]
Once merged, [this PR](https://github.com/VCityTeam/py3dtilers/pull/124) will allow to keep only the selected CityObjects with the flag `--keep_ids` or to exclude some CityObjects with the flag `--exclude_ids`
