### ISSUE TITLE
Wrong transformation or rotation

### ISSUE THREAD

**Issue by laraduarte** [VCityTeam/py3dtilers#128]
Hi,

I tried to convert IFC file and load it in Cesium and although it seems to be in the right location, the model shifts position as you can see in the video below.

Is this a bug? 

https://user-images.githubusercontent.com/1926934/222536607-3760b807-6175-40d1-99fb-64c40e9cc570.mp4

**Comment by SavageChigga** [comment]
I met the same problem which makes my 3d tiles data get wrong position(usually under the ground) and rotation when loaded in cesium. But when using the fme tool it can get the right positon and rotation
