### ISSUE TITLE
ifcObjectGeom retrievObjByGroup missing material

### ISSUE THREAD

**Issue by laraduarte** [VCityTeam/py3dtilers#129]
Hello,

I found a few issues while trying to convert IFC --grouped_by IfcGroup

IfcTiler.py line 43 should be amended to pre_tileset = IfcObjectsGeom.retrievObjByGroup(ifc_file, with_BTH)

![image](https://user-images.githubusercontent.com/1926934/222789313-dda459c1-4668-4786-8725-1b042328906c.png)

then we also need to add with_BTH in ifcObjectGeom.py
![image](https://user-images.githubusercontent.com/1926934/222789408-a3564e81-baa9-4ee2-9fe9-04f3d1281d65.png)
![image](https://user-images.githubusercontent.com/1926934/222789453-24085d2c-88c0-48fc-ab86-1d73c7e5067c.png)

Another issue I found is the grouped_by IfcGroup does not export the material index, I believe that is the reason with the model is completely white.

--grouped_by IfcGroup
![image](https://user-images.githubusercontent.com/1926934/222789776-77e9a977-6173-45eb-b934-b1ee9378dba6.png)

--grouped_by  IfcTypeObject
![image](https://user-images.githubusercontent.com/1926934/222790083-82c92f6e-074c-412e-9b8a-1b8ec923eefb.png)

What can I do to fix the material issue?

Thanks
Lara

**Comment by clementcolin** [comment]
Thank you for your insight, I made a pr (cf #130 ) to add the material when grouping by IfcGroup and support of BTH.

I'm not very sure if the BTH is working well with IfcGroup (or even with the IfcTiler), do not hesitate to post issues if you have any other bugs or missing features.
