### ISSUE TITLE
Enable multi lod contruction of multi-level OBJ files

### ISSUE THREAD

**Issue by EricBoix** [VCityTeam/py3dtilers#140]
Consider the [set of OBJ files](https://gitlab.liris.cnrs.fr/VCityTeam/GRIM-Viz/-/tree/main/MultiLevelTiles/data-test1-5_levels-converted-to-OBJ) representing the same textured object (a monkey considered as a [city sculpture](https://images.squarespace-cdn.com/content/v1/607219fe2328d216aa27ba74/6da1e6ed-0d2a-4794-8fd5-5a06f8f90dd5/Netflix_PiazzaDePapel_06.JPG)) but at different levels of resolution.
Provide py3dtilers with the ability to load such set and construct a LOD hierarchy where each resolution level stands at a different LOD level (think of Russian dolls). Then realize a [py3dTilers demo](https://github.com/VCityTeam/UD-Demo-vcity-py3dtilers-lyon) placing the newly build multi-LOD monkey in a visible place of the City and calibrate the Geometric error (when needed) so that zooming on the monkey displays enhanced levels of resolution. 

Notes: refer to `--geometric_error` and `--texture_lods` tiler options to possibly become `--geometric_lods` together with  `--geometric_error` for the OBJTiler...

**Comment by LorenzoMarnat** [comment]
@EricBoix I started to work on that on [obj_lods branch](https://github.com/VCityTeam/py3dtilers/tree/obj_lods). If the flag `--as_lods` is present, the input models we be placed in a vertical hierarchy. The first input model will be the leaf of the hierarchical tree, the last will be the root.

To create a hierarchy from OBJ models at different resolutions:

```bash
obj-tiler -i G:\Data\Obj\monkey_objs\ -o monkey_3dtiles --as_lods --scale 3 --offset 1843397 5173891 300 --geometric_error 1 4 8 13 21
```

`monkey_objs` contains sorted OBJ models. The first OBJ model is the most detailled one, the last the least detailled

![e0b297906941faf19b59a3f9dd92a142](https://github.com/VCityTeam/py3dtilers/assets/32875283/1952cb7b-0b8f-4ec7-8301-f093953ccef3)

**Comment by elombardi2** [comment]
The implementation is validated for GRIM demo at commit 2d0c2c5 of branch [obj_lods](https://github.com/VCityTeam/py3dtilers/tree/obj_lods).
Branch [obj_lods](https://github.com/VCityTeam/py3dtilers/tree/obj_lods) could be merged into master.
