### ISSUE TITLE
Upgrade python version

### ISSUE THREAD

**Issue by jailln** [VCityTeam/py3dtilers#169]
Python 3.9 is not available in default ppa repositories for ubuntu 22.04. The point of this ticket is to update the required python version for py3dtilers.

I managed to install it though ([instructions](https://itslinuxfoss.com/install-python-3-9-ubuntu-22-04/)).

**Comment by LorenzoMarnat** [comment]
Previous version limit was the IFCOpenShell package (that didn't exist for Python > 3.9). Now IFCOpenShell is available for 3.10, but we have some problems with Numpy for Python3.10:

![image](https://github.com/VCityTeam/py3dtilers/assets/32875283/74cda6a0-ff4e-4a35-919e-a0d4db2950c4)

I'll try to find a solution to support at least 3.9 and 3.10, and hopefully other versions
