### ISSUE TITLE
Apply flake8

### ISSUE THREAD

**Issue by EricBoix** [VCityTeam/py3dtilers#2]
Oslandia last updates [integrates the usage of flake8](https://github.com/Oslandia/py3dtiles/blob/master/.travis.yml).
 - [x] Update setup.py accordingly (done in PR #12 )  
 - [x] fix the coding style errors/warnings...
 - [x] Document it's usage in the readme.md (after running test sessions? )
 - [x] Have CI apply flake8

**Comment by LorenzoMarnat** [comment]
[In this commit](https://github.com/VCityTeam/py3dtilers/commit/569cbe84b6004bd6b995f13a665f8907d9a9a12a)
- lint all the code and fix coding style errors
- add flake8, autopep8 and pytest-flake8 in dev extras
- make Travis check the coding style
- update the [doc](https://github.com/VCityTeam/py3dtilers#coding-style) with coding style
