### ISSUE TITLE
Embed material in b3dm 

### ISSUE THREAD

**Issue by clementcolin** [VCityTeam/py3dtilers#20]
Currently, It seems that there is no way to add a specific material to an object in the B3DM produced. Looking at the [specification](https://github.com/KhronosGroup/glTF/blob/main/specification/2.0/figures/gltfOverview-2.0.0b.png), it should be possible to do so.
It would be interesting to add such feature.
For example, we could then add a color for each building, using their texture to be a little more realist than a white building.

Maybe [pg2b3dm](https://github.com/Geodan/pg2b3dm) have this feature

**Comment by LorenzoMarnat** [comment]
It is now possible to create materials (single-colored or with texture uri) with this [PR](https://github.com/VCityTeam/py3dtilers/pull/33)
