### ISSUE TITLE
Add support for textures to ObjTiler

### ISSUE THREAD

**Issue by webanck** [VCityTeam/py3dtilers#26]
Currently, material textures specified in a `.mtl` file next to the `.obj` are lost when convertinf between `.obj` (Wavefront) files and  3DTiles.
It would be nice to embed the specified texture coordinates and the textures files in the generated 3DTiles.

**Comment by LorenzoMarnat** [comment]
[This PR](https://github.com/VCityTeam/py3dtilers/pull/28) (merged on `master`) allows to created textured 3DTiles from textured OBJ.

Use the flag `--with_texture` to read the texture:
```bash
obj-tiler --paths path/to/textured/obj --with_texture
```

**Comment by charly-perspectives** [comment]
Hello, 
I would like to convert an .obj file with materials but no texture. 
I feel like this is not implemented yet, can you confirm this?

**Comment by LorenzoMarnat** [comment]
Hello,
Indeed, we only support textured materials for OBJ files. And unfortunatly, we have no plans to work on supporting all OBJ materials at this time.
