### ISSUE TITLE
IfcTiler unit convertions should be located in a single place

### ISSUE THREAD

**Issue by EricBoix** [VCityTeam/py3dtilers#4]
If you look for occurrences of the `100` integer in the code located in the IfcTiler module
(e.g. in ifcObjectGeom.py) chances are they concern conversions from centimeters to
meters (used in 3dTiles). Such conversions:
 - should not be scattered in the code but localized in a unique place (because of [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself). That location can now document it's choices and address many units.
 - should not hardwire  the unit choice of some input. The code actually works because the considered 
    input IFC files were using centimeters. What about other input possibilities ? They should be dealt with
    automatically
 - should be documented (why a hundred a not a thousand) ?

**Comment by clementcolin** [comment]
Done in [PR](https://github.com/VCityTeam/py3dtiles/pull/5)
