### ISSUE TITLE
Reduce computation time of Tilers when adding textures

### ISSUE THREAD

**Issue by LorenzoMarnat** [VCityTeam/py3dtilers#42]
Adding textures to the 3DTiles with CityTiler multiply the computation by x50.

- [x] Look for Python profiling tools
- [x] Try to reduce computation time

**Comment by LorenzoMarnat** [comment]
This [PR](https://github.com/VCityTeam/py3dtilers/pull/48) reduces the computation time of textured 3DTiles by querying the images only once per tile. We used to query the images for each surface.

**Comment by LorenzoMarnat** [comment]
According to this [Pillow's issue](https://github.com/python-pillow/Pillow/issues/1211#issuecomment-98800656), changing the compression level when saving images allows to reduce computation time.

```python
atlasImg.save(Texture.folder + '/tiles/ATLAS_' + str(tile_number) + '.png', compress_level=3)
```

| Compress level | Computation time (s) | Atlas size (mo) |
| --- | --- | --- |
| 6 | 68.65 | 76.0 |
| 3 | 60.90 | 77.0 |
| 1 | 49.45 | 89.4 |

**Comment by jailln** [comment]
Is it a lossy or a lossless compression ? Maybe it could be a parameter offered by py3dtiles with a default value ?

**Comment by LorenzoMarnat** [comment]
Pillow uses the lossless data compression [zlib](https://www.euccas.me/zlib/) to compress images

**Comment by LorenzoMarnat** [comment]
Pillow image compression will be handled with the [compression issue](https://github.com/VCityTeam/py3dtilers/issues/46). Closing
