### ISSUE TITLE
Compress textures and geometries

### ISSUE THREAD

**Issue by LorenzoMarnat** [VCityTeam/py3dtilers#46]
We should be able to create compressed 3DTiles (geometries and textures).

- Is there any existing tool/library for glTF compression in Python ?
- Should we compress 3DTiles during computation (in the Tilers) or with an external tool/script ?

Some tests to compress 3DTiles have been made with JS tools ([see this doc](https://github.com/VCityTeam/UD-SV/blob/master/ImplementationKnowHow/3DTilesCompression.md))

About [Pillow image compression](https://github.com/VCityTeam/py3dtilers/issues/42#issuecomment-1025945776). `compress_level` could become [a parameter of py3dtilers](https://github.com/VCityTeam/py3dtilers/issues/42#issuecomment-1025954359)

**Comment by jailln** [comment]
From what I know, the most used algorithms to compress geometries are [meshoptimizer](https://meshoptimizer.org/) and [draco](https://google.github.io/draco/). Draco is more popular and it performs better on geometries (while meshopt performs better on animations). The official draco transcoder is in C++ but there seems to be a [python wrapping](https://github.com/seung-lab/DracoPy) (don't know what it's worth though). Threejs and itowns can decode gltf with draco encoded geometries (see [this](https://threejs.org/docs/index.html?q=dra#examples/en/loaders/DRACOLoader) and [this](https://github.com/iTowns/itowns/blob/master/examples/3dtiles_25d.html#L82)).

Regarding textures, ktx v2 container for basisu (Basis Universal) textures seems to currently be the most efficient in the gltf ecosystem ([supported by threejs](https://threejs.org/docs/index.html?q=ktx2#examples/en/loaders/KTX2Loader) and itowns with a few modifications (I will open a PR with these)).

Some interesting links about KTX2 and Basis Universal:
  * [Short presentation article](https://www.khronos.org/blog/google-and-binomial-contribute-basis-universal-texture-format-to-khronos-gltf-3d-transmission-open-standard)
  * [Basis Universal](https://github.com/binomialLLC/basis_universal)
  * [gltf extension](https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_texture_basisu)
  * [KTX2 spec](https://github.khronos.org/KTX-Specification/)

One good tool to transform gltf files and to apply such transformations is [gltf-transform](https://gltf-transform.donmccurdy.com/) but it's written in JS, sadly for py3dtiles :)

**Comment by LorenzoMarnat** [comment]
Using `quality` parameter when saving atlases as images seems to be an easy way to reduce the size of the images (the images must be saved as JPEG).

```python
atlasImg.save(Path(Texture.folder, 'tiles', 'ATLAS_' + str(tile_number) + '.jpeg'), quality=10)
```

With `quality=10`, the quality of the images will be reduced by 90%. Here's an example (the first picture is 10% quality, the second 100%):

![lyon1_10quality](https://user-images.githubusercontent.com/32875283/164229806-6af6a085-3bb7-4b2e-8af4-5ea3880d9f2f.png)

![lyon1_100quality](https://user-images.githubusercontent.com/32875283/164229821-409b5030-d623-4cf2-b3ef-774c5c7bf211.png)

Lowering the quality by 90% reduces the size of the atlases by ~90%. The CityTiler also computes the 3DTiles way faster. In UD-Viz, the 3DTiles load faster and the quality difference between 100% and 10% is not very noticeable.

`quality` could become a CL option. I'll make some tests and benchmarks.

**Comment by LorenzoMarnat** [comment]
Some interisting benchmarks from 3D Tiles 1.1 [Community Standard Justification](https://portal.ogc.org/files/100660)
![image](https://user-images.githubusercontent.com/32875283/167853027-80c16ada-a2c2-4529-af23-fd95c298bf94.png)

![image](https://user-images.githubusercontent.com/32875283/167853078-7af1e150-ad77-44f0-9762-7f2397e0009e.png)

![image](https://user-images.githubusercontent.com/32875283/167853122-731ca8fe-d904-48db-8afd-278914138d0a.png)

**Comment by jailln** [comment]
Nice!! Too bad they haven't tried glb + ktx2/basis/etc1s + draco which achieves the best results from similar tests I did. Also, do you know the compression level of the jpeg files ?

**Comment by LorenzoMarnat** [comment]
For some reason, they didnt try ktx2/basis/etc1s + draco. I didn't found why.

For jpeg, they use 80% quality
![image](https://user-images.githubusercontent.com/32875283/167858116-776972fe-ebda-4f65-856f-7e8ab6577e9b.png)

**Comment by jailln** [comment]
Thanks for the clarifications! JPEG achieves nice results! Too bad they don't show screenshots of each case to also compare the results visually

**Comment by LorenzoMarnat** [comment]
Impact of the `--quality` flag (that will be implemented with [this PR](https://github.com/VCityTeam/py3dtilers/pull/97)) on the size of the images.

Quality (%) | Size (Mo)
-- | --
100 | 27,5
99 | 24,2
97 | 17,9
95 | 14,4
90 | 10
80 | 6,81
70 | 5,48
60 | 4,66
50 | 4,13
40 | 3,63
30 | 3,12
20 | 2,49
10 | 1,73
1 | 1,03

![image](https://user-images.githubusercontent.com/32875283/170962084-67d92ba5-5f3c-4a79-b24f-8ba9fe9f3dd9.png)

**Comment by LorenzoMarnat** [comment]
Downsizing images seems to be a very efficient way to reduce the size of the images. See [texture LODs issue](https://github.com/VCityTeam/py3dtilers/issues/109)

**Comment by LorenzoMarnat** [comment]
Issues in Oslandia's Py3DTiles:

- [Draco compression](https://gitlab.com/Oslandia/py3dtiles/-/issues/100)
- [Texture compression](https://gitlab.com/Oslandia/py3dtiles/-/issues/177)
