### ISSUE TITLE
Provide the ability to configure geometric error

### ISSUE THREAD

**Issue by jailln** [VCityTeam/py3dtilers#52]
The [geometric error](https://github.com/CesiumGS/3d-tiles/tree/main/specification#geometric-error) defines when a tile should be displayed by the client (depending on the distance to the camera). This should be configurable (and editable with the `TilesetReader`). It would also allow to define when to change between LOD1 or LOA and the most detailed tiles for instance.

**Comment by LorenzoMarnat** [comment]
Implemented in [this PR](https://github.com/VCityTeam/py3dtilers/pull/79)
