### ISSUE TITLE
[CityTiler] Add progress information about the transformation 

### ISSUE THREAD

**Issue by jailln** [VCityTeam/py3dtilers#54]
It could be useful to add progress information of the transformation process, at least the different steps and in the best case a progress bar (e.g. like for the [point cloud transformation tiler](https://gitlab.com/Oslandia/py3dtiles/-/blob/master/py3dtiles/convert.py)).

**Comment by LorenzoMarnat** [comment]
The tilers now display a progress bar with the number of tiles created / tiles to create. The CityTiler also prints messages at the begining of each main step of the process. In a [future developpement](https://github.com/VCityTeam/py3dtilers/issues/41), the tilers will display more information at the end.

Do you think the CityTiler displays enough information ? Should it be more verbose (it could be with a `--verbose` flag for example) ? If it should be more verbose, what information would you like to see ?

**Comment by jailln** [comment]
I saw these recent improvements, the displays are good and answer this issue, thanks !
