### ISSUE TITLE
Explictly express that the nodes of a GeometryTree are GeometryNodes

### ISSUE THREAD

**Issue by EricBoix** [VCityTeam/py3dtilers#60]
Some attentive reading of usages of `GeometryTree` (one must look at derived classes) shows that this is tree of `GeometryNodes` (in fact derived classes of GeometryNodes).
Provide some hints for a developer to easily get that understanding, just by reading `geometry_tree.py`.
Maybe the comments could be stating thits ?
Or maybe the usage of type hinting would be even clearer ?
The constructor could then be written something like
```python
def __init__(self, root_nodes: list[GeometryNode]):
```

**Comment by LorenzoMarnat** [comment]
Type hint added in commit 3e34d7210841f396091de2c56a492f8dd25760d8
