### ISSUE TITLE
Clarify what GeometryTree.leaf_nodes are for (and what is their type).

### ISSUE THREAD

**Issue by EricBoix** [VCityTeam/py3dtilers#61]
The following concerns the `geometry_tree.py` file.

If we consider the [graph theory](https://en.wikipedia.org/wiki/Tree_(graph_theory)) terminology, a (tree) leaf is a node (vertex) without sub-nodes. Now, when given a root (node) of a tree one can navigate to the leafs of the tree. 
Hence storing them again in leaf_nodes seems only justified on optimization purposes.
But then leaf_nodes must be kept updated when the tree gets edited, which places some constraint on the code.
Are leaf_nodes and leafs (of the root_nodes) (where leafs is a "function" of a node/root_node) the same thing ?
Document/clarify what lead_nodes are for...

In addition, there is no setter for lead_nodes. Having a setter would be a good place to locate/document the type of leaf_nodes. What are leaf_nodes types ? ObjectsToTile ? GeometryNodes ? Derived classes of GeometryNodes ?

**Comment by LorenzoMarnat** [comment]
With [this commit](https://github.com/VCityTeam/py3dtilers/commit/0333e4ea3e16bff775f89ccd68e737a58bc34c72), the leaf nodes are found by the method `get_leaf_nodes` of the `GeometryTree`. This method always starts from the root nodes. The attribute `leaf_nodes` no longer exist.
