### ISSUE TITLE
Attribute Error --> tileset-merger

### ISSUE THREAD

**Issue by t3rr0n3** [VCityTeam/py3dtilers#75]
Hi
I'm having problems with TilesetMerger. When I launch it, the result is:

Traceback (most recent call last):
  File "/home/user/py3dtilers/venv/bin/tileset-merger", line 11, in <module>
    load_entry_point('py3dtilers', 'console_scripts', 'tileset-merger')()
  File "/home/user/py3dtilers/py3dtilers/TilesetReader/TilesetMerger.py", line 104, in main
    tilesets = merger.reader.read_tilesets(paths)
AttributeError: 'TilesetReader' object has no attribute 'read_tilesets'

My Debian specification is:

# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="[https://www.debian.org/"](https://www.debian.org/%22)
SUPPORT_URL="[https://www.debian.org/support"](https://www.debian.org/support%22)
BUG_REPORT_URL="[https://bugs.debian.org/"](https://bugs.debian.org/%22)

# uname -a
Linux vm-lxosgeo-test 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) x86_64 GNU/Linux

# python3 --version
Python 3.9.2

Could anyone help me?
Thank you

**Comment by LorenzoMarnat** [comment]
Hello,
Are you using the last version of [py3dtiles' Tiler branch]() ? From your installation of py3dtileRs, uninstall py3dtiles then reinstall py3dtileRs. It will pull the up-to-date version of py3dtiles.

```bash
(venv) py3dtilers$ pip uninstall py3dtiles
(venv) py3dtilers$ pip install -e .
```

**Comment by t3rr0n3** [comment]
Thank you, Attribute Error was solved.
I found this message:

(venv) user@vm-lxosgeo-test:~/py3dtilers$ tileset-merger --path /home/user/Scrivania/3dtiles/LAS0110_6706_RGB/ /home/user/Scrivania/3dtiles/LAS0120_6706_RGB/ --out /home/user/Scrivania/tileset_reader_output/merged_tileset
Couldn't read the tileset /home/user/Scrivania/3dtiles/LAS0110_6706_RGB/
Couldn't read the tileset /home/user/Scrivania/3dtiles/LAS0120_6706_RGB/
Warning: should have checked for existing children first?
Warning: defaulting TileSet's unset 'Geometric Error'.
Warning: defaulting Tile's unset 'Geometric Error'.
Warning: Bounding Volume Box is not defined.
Warning: invalid Bounding Volume Box cannot be prepared.

I specify that I am using as input two tileset folders generated from LAS files, but I do not know what programm was used to convert them.

Thank you

**Comment by LorenzoMarnat** [comment]
The TilesetMerger from py3dtilers works only on `.b3dm` files ([Batched 3D models](https://github.com/CesiumGS/3d-tiles/blob/main/specification/TileFormats/Batched3DModel/README.md)).

If you want to convert or merge LAS/point clouds, you should use [Oslandia's py3dtiles](https://gitlab.com/Oslandia/py3dtiles). You can find the [comand line usage here](https://gitlab.com/Oslandia/py3dtiles/-/blob/master/docs/cli.rst). The code of the point clouds merger can be found in [merger.py](https://gitlab.com/Oslandia/py3dtiles/-/blob/master/py3dtiles/merger.py).
