### ISSUE TITLE
[CityTiler] "Dancing buildings"

### ISSUE THREAD

**Issue by jailln** [VCityTeam/py3dtilers#77]
The geometries of the 3D Tiles produced with the CityTiler move alone when moving the camera:

https://user-images.githubusercontent.com/16967916/157007761-74beab45-ad8f-40f9-aec2-5aea0ad13259.mp4

This happens for conversions with and without textures and since PR #71 . I reproduce this on iTowns and Cesium and I don't reproduce it with tilesets produced before #71 with the same iTowns/Cesium apps.

**Comment by LorenzoMarnat** [comment]
Which CRS are you using ? Do you know if it happens in any CRS ?

**Comment by jailln** [comment]
It seems related to the CRS (transformation) indeed: In my first message, I converted from EPSG:3945 to EPSG:4978 and I just tried with a dataset of Lyon without CRS transformation and the bug is gone.

**Comment by LorenzoMarnat** [comment]
I think the error comes from the `transform` and `boundingVolume` of the tiles in the tileset.json. 

For a same tile (projected in PESG:4978), with master branch:

```json
      {
        "boundingVolume": {
          "box": [
            172.20416069030762, -577.5076789855957, -170.31637573242188,
            224.00000190734863, 0.0, 0.0, 0.0, 692.2968864440918, 0.0, 0.0, 0.0,
            273.75
          ]
        },
        "geometricError": 1,
        "refine": "REPLACE",
        "content": { "uri": "tiles/0.b3dm" },
        "transform": [
          1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0,
          4440989.296, 375313.555, 4547598.566, 1.0
        ]
      },
```

With PR branch:


```json
      {
        "boundingVolume": {
          "box": [
            2598789.75, -4801335.25, 4547209.625, 224.0, 0.0, 0.0, 0.0, 692.25,
            0.0, 0.0, 0.0, 273.875
          ]
        },
        "geometricError": 1,
        "refine": "REPLACE",
        "content": { "uri": "tiles/0.b3dm" },
        "transform": [
          1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0,
          1842371.867, 5176071.129, 218.639, 1.0
        ]
      },
```

The correct values are those from master branch. I'll see what goes wrong on PR branch

**Comment by jailln** [comment]
Nice, thanks! I should have put this issue directly in the PR, I thought that it was already merged, sorry for that.

**Comment by LorenzoMarnat** [comment]
It should be fixed on the PR branch. 

The problem was coming from the centroid used when creating a tile. We were using the centroid of the whole tileset, but this centroid is wrong if we reproject the tileset, since some tiles will be in the new CRS and others (not transformed yet) will still be in the old CRS.

**Comment by jailln** [comment]
It's fixed, thanks!
