### ISSUE TITLE
[CityTiler] Weird vertices

### ISSUE THREAD

**Issue by jailln** [VCityTeam/py3dtilers#78]
The 3D Tiles created with the CityTiler have weird vertices: it seems that all buildings are connected with a vertex, while they are not in the original CityGML:

![lyon-1-wireframe](https://user-images.githubusercontent.com/16967916/157010114-893f639d-6a19-4788-87e6-114e6d2627a5.png)

![image](https://user-images.githubusercontent.com/16967916/157010135-6651c61b-17cc-471b-badf-909af61383a8.png)

I reproduced it on different input CityGML and the visualisation is the same in iTowns and Cesium. It happens whether the transformation is ran with or without textures. I reproduce this issue before and and after #71 so it does not seem related to this PR and neither to issue #77. Note that it has no visual impact when not in wireframe mode.

**Comment by LorenzoMarnat** [comment]
If you export the tileset as OBJ during the creation (with `--obj name.obj`) and open this OBJ in a mesh viewer, do you see those weird vertices ?

**Comment by jailln** [comment]
No I don't. Do you think it comes from the gltf writer ?

**Comment by LorenzoMarnat** [comment]
I can see that those weird lines also appears in the [Cesium 3D Tiles inspector example](https://sandcastle.cesium.com/gallery/3D%20Tiles%20Inspector.html):

![image](https://user-images.githubusercontent.com/32875283/157239656-e92fcf85-31c5-4b8a-a25f-b003459b5987.png)

There is an [issue open](https://github.com/CesiumGS/cesium/issues/9066) on Cesium Github about this.

**Comment by jailln** [comment]
Oh ok, well spoted! I will look into why it's the same in iTowns, but I guess we can close this issue for now, as it has no visual impact on the geometry when it's not wireframe anyway.
However, it is not always the case in Cesium, e.g. here for a dataset created with FME:
![image](https://user-images.githubusercontent.com/16967916/157248058-ae4abbe0-3e69-4410-8921-369b07e620c1.png)

**Comment by LorenzoMarnat** [comment]
Yes, I wonder if its linked to the batch. Since we create many batched features in a single glTF mesh, maybe the wireframe debug tool creates a thread between all the vertices of the mesh without using the batchIDs to seperate the features.

**Comment by jailln** [comment]
Yes that's a good lead. However, it's weird that it only does it on some tilesets. It may also be combined with the fact that when in wireframe mode it interprets the geometry buffer (representing batched geometries) directly as lines instead of triangles and since all geometries are batched, it draws a line between all points instead of creating triangles.
