### ISSUE TITLE
tileset-merger not setting uri of tile content

### ISSUE THREAD

**Issue by mittermichal** [VCityTeam/py3dtilers#88]
hello,
`tileset-merger --paths tests/tileset_reader_test_data/textured_cube`
yields:
```json
{"uri":"Dummy content set by TileContent:__init__()"}
```
It happens after this commit: 522d946864e90e073c0722a058e939dc28535b03

**Comment by LorenzoMarnat** [comment]
Hello, thanks for the issue. It is fixed on master (with commit 33970dc5d97684ed9cc1f732cddcd6bed41038d2).

The `tileset-merger` was using the [write_as_json](https://github.com/VCityTeam/py3dtiles/blob/Tiler/py3dtiles/tileset.py#L113) method (which writes only the JSON part of the tileset) while it should use [write_to_directory](https://github.com/VCityTeam/py3dtiles/blob/Tiler/py3dtiles/tileset.py#L86) (writes the JSON and the tiles). It was indeed broken after the commit 522d946864e90e073c0722a058e939dc28535b03

**Comment by mittermichal** [comment]
thanks!
